repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: b5f1f47c014ac21cf0a68c469a1b378f23893d0c # v1.6.0
    hooks:
      - id: baseline
        name: Ministry of Justice - Security scan

  - repo: local
    hooks:
      - id: lint
        name: Lint check
        entry: npm run validate:all
        language: system
        pass_filenames: false

      - id: spellcheck
        name: Spell check
        entry: npm run spellcheck
        language: system
        pass_filenames: false

      - id: uv-version-sync
        name: uv version sync
        entry: python3 utils/check_uv_sync.py
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80 # v0.15.12
    hooks:
      - id: ruff-check
        name: Ruff Check
        args: [ --fix ]
      - id: ruff-format
        name: Ruff Format
  
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 73c2d77a42a113aee9e4b748c24937f09557b82d # 0.11.24
    hooks:
      - id: uv-lock