name: Publish audit-cli python package

on:
  release:
    types: [published] # Trigger on release-please created release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: "3.14"
          enable-cache: true
      - name: Build audit-cli Package
        run: uv build
      
      - name: Publish audit-cli Package to GitHub Packages
        run: |
          uv publish \
            --publish-url https://test.pypi.org/legacy/ \
            --check-url https://test.pypi.org/simple/ \
            dist/*
      