name: Pytest
run-name: Pytest

on:
  push:
    branches:
      - "**"
  pull_request:

permissions: {}

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv & Set Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --group dev

      - name: Run pytest (exclude integration)
        run: uv run pytest -m "not integration" -q
